version: '2.1'

services:
  db:
    image: helloworld_db
    build:
      context: ./HelloWorldWithDatabase/db
      dockerfile: Dockerfile
    ports:
       - "1433:1433"

  web:
    image: helloworld_web
    build:
      context: .\HelloWorldWithDatabase
      dockerfile: Dockerfile
    environment:
      CONNECTION_STRING: "Server=db;Database=SampleDB01;User ID=sa; Password=Password123;Integrated Security=False"
    depends_on:
      - "db"

  api:
    image: api
    build:
      context: .\Api
      dockerfile: Dockerfile
