version: '2.1'

services:
  db:
    image: helloworldweb_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
       - "1433:1433"

  helloworldweb:
    image: helloworldweb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"