version: '2.1'

services:
  db:
    image: helloworld_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
       - "1433:1433"

  web:
    image: helloworld_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"