CREATE DATABASE [SampleDB01];
GO

USE [SampleDB01];
GO

CREATE TABLE dbo.Table01
(PKID INT IDENTITY(1,1) PRIMARY KEY,
 ColA VARCHAR(10),
 ColB VARCHAR(10),
 ColC DATETIME);
GO

INSERT INTO dbo.Table01
(ColA,ColB,ColC)
VALUES
(REPLICATE('A',10),REPLICATE('B',10),GETUTCDATE());
GO 10
